# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 285)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.le_volume = QtWidgets.QLineEdit(Dialog)
        self.le_volume.setObjectName("le_volume")
        self.gridLayout.addWidget(self.le_volume, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.le_title = QtWidgets.QLineEdit(Dialog)
        self.le_title.setObjectName("le_title")
        self.gridLayout.addWidget(self.le_title, 0, 1, 1, 1)
        self.pb_add = QtWidgets.QPushButton(Dialog)
        self.pb_add.setText("")
        self.pb_add.setObjectName("pb_add")
        self.gridLayout.addWidget(self.pb_add, 6, 1, 1, 1)
        self.le_price = QtWidgets.QLineEdit(Dialog)
        self.le_price.setObjectName("le_price")
        self.gridLayout.addWidget(self.le_price, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.le_roasting = QtWidgets.QLineEdit(Dialog)
        self.le_roasting.setObjectName("le_roasting")
        self.gridLayout.addWidget(self.le_roasting, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.le_taste = QtWidgets.QLineEdit(Dialog)
        self.le_taste.setObjectName("le_taste")
        self.gridLayout.addWidget(self.le_taste, 3, 1, 1, 1)
        self.le_type = QtWidgets.QLineEdit(Dialog)
        self.le_type.setObjectName("le_type")
        self.gridLayout.addWidget(self.le_type, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "молотый/в зернах:"))
        self.label_6.setText(_translate("Dialog", "цена:"))
        self.label_3.setText(_translate("Dialog", "степень обжарки:"))
        self.label_5.setText(_translate("Dialog", "описание вкуса:"))
        self.label_7.setText(_translate("Dialog", "объем упаковки:"))
        self.label_2.setText(_translate("Dialog", "название сорта:"))
